/*
 * Focused D3D9 PE conformance harness driver.
 *
 * Wine behavioral oracle:
 * - dlls/d3d9/tests/d3d9ex.c
 * - dlls/d3d9/tests/device.c
 * - dlls/d3d9/tests/stateblock.c
 * Wine commit 6e073d28dee3af7f4c965daec94644e0f9f92727.
 *
 * Per-domain test bodies live in d3d9_conformance_<bucket>.c. This file
 * owns the unique definitions of the shared counters declared extern in
 * d3d9_conformance_fixtures.h, the test dispatch table, and main().
 */

#include "d3d9_conformance_fixtures.h"

const char *current_test;
unsigned int checks_run;
unsigned int checks_failed;
unsigned int tests_skipped;

static const struct test_case tests[] =
{
    {"factory_validation_return_codes", test_factory_validation_return_codes},
    {"factory_caps_edge_matrix", test_factory_caps_edge_matrix},
    {"invalid_multisample_render_target_quality",
            test_invalid_multisample_render_target_quality},
    {"device_display_mode_adapter_format",
            test_device_display_mode_adapter_format},
    {"factory_base_vs_ex_qi", test_factory_base_vs_ex_qi},
    {"ex_created_normal_device_qi", test_ex_created_normal_device_qi},
    {"display_mode_ex_size_filter_smoke",
            test_display_mode_ex_size_filter_smoke},
    {"present_parameter_validation", test_present_parameter_validation},
    {"present_parameter_normalization", test_present_parameter_normalization},
    {"swapchain_backbuffer_getter_policy",
            test_swapchain_backbuffer_getter_policy},
    {"additional_swapchain_backbuffer_bounds",
            test_additional_swapchain_backbuffer_bounds},
    {"ex_create_reset_mode_validation",
            test_ex_create_reset_mode_validation},
    {"scene_invalid_transitions", test_scene_invalid_transitions},
    {"vertex_declaration_fvf_policy", test_vertex_declaration_fvf_policy},
    {"fvf_decl_management", test_fvf_decl_management},
    {"unused_declaration_type", test_unused_declaration_type},
    {"get_set_vertex_shader", test_get_set_vertex_shader},
    {"vertex_shader_constant", test_vertex_shader_constant},
    {"get_set_pixel_shader", test_get_set_pixel_shader},
    {"pixel_shader_constant", test_pixel_shader_constant},
    {"unsupported_shaders", test_unsupported_shaders},
    {"shader_unsupported_stage_variants",
            test_shader_unsupported_stage_variants},
    {"ex_shader_validation_policy", test_ex_shader_validation_policy},
    {"texture_stage_states", test_texture_stage_states},
    {"sampler_state_edges", test_sampler_state_edges},
    {"light_enable_state", test_light_enable_state},
    {"fpu_setup", test_fpu_setup},
    {"limits", test_limits},
    {"viewport_scissor_state_getters", test_viewport_scissor_state_getters},
    {"clip_plane_state_getters", test_clip_plane_state_getters},
    {"null_stream_state", test_null_stream_state},
    {"null_stream_shader_draw_policy",
            test_null_stream_shader_draw_policy},
    {"set_stream_source_state", test_set_stream_source_state},
    {"stream_source_frequency_state", test_stream_source_frequency_state},
    {"stream_source_vb_offset_alignment_policy",
            test_stream_source_vb_offset_alignment_policy},
    {"stream_source_null_layout_policy",
            test_stream_source_null_layout_policy},
    {"stream_source_zero_stride_policy",
            test_stream_source_zero_stride_policy},
    {"stream_source_null_offset_alignment_policy",
            test_stream_source_null_offset_alignment_policy},
    {"get_set_texture", test_get_set_texture},
    {"set_palette_roundtrip", test_set_palette_roundtrip},
    {"palette_alpha_caps_policy", test_palette_alpha_caps_policy},
    {"palette_current_entry_isolation",
            test_palette_current_entry_isolation},
    {"multi_adapter", test_multi_adapter},
    {"device_creation_parameters_policy",
            test_device_creation_parameters_policy},
    {"device_parent_caps_getter_policy",
            test_device_parent_caps_getter_policy},
    {"device_raster_status_bounds", test_device_raster_status_bounds},
    {"pixel_format_window_policy", test_pixel_format_window_policy},
    {"stateblock_invalid_type_recording_invalid_calls",
            test_stateblock_invalid_type_recording_invalid_calls},
    {"shader_constant_apply", test_shader_constant_apply},
    {"shader_constant_stateblock_cross_stage",
            test_shader_constant_stateblock_cross_stage},
    {"vdecl_apply", test_vdecl_apply},
    {"stateblock_transform_capture_apply",
            test_stateblock_transform_capture_apply},
    {"stateblock_multiply_transform_capture",
            test_stateblock_multiply_transform_capture},
    {"private_data_iunknown_ownership_smoke",
            test_private_data_iunknown_ownership_smoke},
    {"private_data_resource_wrappers",
            test_private_data_resource_wrappers},
    {"private_data_replace_and_size_policy",
            test_private_data_replace_and_size_policy},
    {"resource_lock_error_policy", test_resource_lock_error_policy},
    {"surface_lockrect_subrect_offset_policy",
            test_surface_lockrect_subrect_offset_policy},
    {"compressed_surface_lockrect_block_offset",
            test_compressed_surface_lockrect_block_offset},
    {"surface_reentrant_lock_preserves_output",
            test_surface_reentrant_lock_preserves_output},
    {"texture_reentrant_lock_preserves_output",
            test_texture_reentrant_lock_preserves_output},
    {"texture_level_surface_unlock_policy",
            test_texture_level_surface_unlock_policy},
    {"surface_double_unlock_pool_policy",
            test_surface_double_unlock_pool_policy},
    {"mipmap_surface_update_lock_policy",
            test_mipmap_surface_update_lock_policy},
    {"vb_lock_flags", test_vb_lock_flags},
    {"pinned_buffers_d3dusage_policy",
            test_pinned_buffers_d3dusage_policy},
    {"writeonly_vertex_buffer_readback_policy",
            test_writeonly_vertex_buffer_readback_policy},
    {"vertex_buffer_alignment", test_vertex_buffer_alignment},
    {"surface_alignment", test_surface_alignment},
    {"surface_dimensions", test_surface_dimensions},
    {"texture_auto_mipmap_level_count",
            test_texture_auto_mipmap_level_count},
    {"base_texture_metadata_iface_policy",
            test_base_texture_metadata_iface_policy},
    {"texture_autogen_filter_level_policy",
            test_texture_autogen_filter_level_policy},
    {"surface_format_null_policy", test_surface_format_null_policy},
    {"resource_type", test_resource_type},
    {"texture_level_surface_desc_parity",
            test_texture_level_surface_desc_parity},
    {"cube_texture_face_desc_parity", test_cube_texture_face_desc_parity},
    {"resource_get_device_wrapper_policy",
            test_resource_get_device_wrapper_policy},
    {"index_buffer_desc_binding_policy",
            test_index_buffer_desc_binding_policy},
    {"vertex_buffer_desc_binding_policy",
            test_vertex_buffer_desc_binding_policy},
    {"texture_surface_container_policy",
            test_texture_surface_container_policy},
    {"cube_texture_level_surface_policy",
            test_cube_texture_level_surface_policy},
    {"volume_resource_container_desc", test_volume_resource_container_desc},
    {"volume_container_interface_policy",
            test_volume_container_interface_policy},
    {"volume_mipmap_level_desc_policy",
            test_volume_mipmap_level_desc_policy},
    {"volume_block_lock_layout", test_volume_block_lock_layout},
    {"volume_blocks_compressed_layout_policy",
            test_volume_blocks_compressed_layout_policy},
    {"volume_lockbox_bounds_offset_policy",
            test_volume_lockbox_bounds_offset_policy},
    {"vendor_format_public_api_policy",
            test_vendor_format_public_api_policy},
    {"resource_priority_roundtrip", test_resource_priority_roundtrip},
    {"resource_priority_pool_policy", test_resource_priority_pool_policy},
    {"base_vidmem_accounting_policy", test_base_vidmem_accounting_policy},
    {"ex_vidmem_accounting_policy", test_ex_vidmem_accounting_policy},
    {"texture_lod_policy", test_texture_lod_policy},
    {"update_texture_pool_copy_2d", test_update_texture_pool_copy_2d},
    {"shared_handle_policy", test_shared_handle_policy},
    {"ex_shared_handle_policy", test_ex_shared_handle_policy},
    {"ex_user_memory_lock_identity", test_ex_user_memory_lock_identity},
    {"creation_failure_out_pointers", test_creation_failure_out_pointers},
    {"create_rt_ds_failure_policy", test_create_rt_ds_failure_policy},
    {"get_render_target_data_policy", test_get_render_target_data_policy},
    {"render_target_device_mismatch", test_render_target_device_mismatch},
    {"create_depth_stencil_surface_ex", test_create_depth_stencil_surface_ex},
    {"ex_adapter_luid_display_mode", test_ex_adapter_luid_display_mode},
    {"ex_adapter_display_mode_null_rotation",
            test_ex_adapter_display_mode_null_rotation},
    {"ex_adapter_mode_enum_bounds", test_ex_adapter_mode_enum_bounds},
    {"ex_swapchain_display_mode", test_ex_swapchain_display_mode},
    {"ex_swapchain_display_mode_null_rotation",
            test_ex_swapchain_display_mode_null_rotation},
    {"ex_frame_latency_state", test_ex_frame_latency_state},
    {"lockable_backbuffer_lock_policy", test_lockable_backbuffer_lock_policy},
    {"nonlockable_backbuffer_getdc_policy",
            test_nonlockable_backbuffer_getdc_policy},
    {"reset_lockable_backbuffer_policy",
            test_reset_lockable_backbuffer_policy},
    {"swapchain_multisample_reset", test_swapchain_multisample_reset},
    {"fullscreen_window_position_restore",
            test_fullscreen_window_position_restore},
    {"ex_user_memory_getdc_dib_identity",
            test_ex_user_memory_getdc_dib_identity},
    {"ex_user_memory_getdc_format_policy",
            test_ex_user_memory_getdc_format_policy},
    {"swapchain_get_display_mode_ex_policy",
            test_swapchain_get_display_mode_ex_policy},
    {"ex_get_adapter_luid_policy", test_ex_get_adapter_luid_policy},
    {"ex_get_adapter_display_mode_ex_policy",
            test_ex_get_adapter_display_mode_ex_policy},
    {"backbuffer_resize_present_parameter_policy",
            test_backbuffer_resize_present_parameter_policy},
    {"multi_device_independent_state",
            test_multi_device_independent_state},
    {"mode_change_focus_swap_policy",
            test_mode_change_focus_swap_policy},
    {"reset_fullscreen_focus_window_policy",
            test_reset_fullscreen_focus_window_policy},
    {"window_position_present_parameter_policy",
            test_window_position_present_parameter_policy},
    {"visual_float_texture_format_policy",
            test_visual_float_texture_format_policy},
    {"visual_g16r16_texture_format_policy",
            test_visual_g16r16_texture_format_policy},
    {"visual_volume_v16u16_format_policy",
            test_visual_volume_v16u16_format_policy},
    {"visual_srgb_texture_caps_policy",
            test_visual_srgb_texture_caps_policy},
    {"visual_srgb_write_caps_policy",
            test_visual_srgb_write_caps_policy},
    {"visual_volume_srgb_caps_policy",
            test_visual_volume_srgb_caps_policy},
    {"visual_volume_dxtn_format_policy",
            test_visual_volume_dxtn_format_policy},
    {"visual_signed_formats_caps_policy",
            test_visual_signed_formats_caps_policy},
    {"visual_z_range_render_state_policy",
            test_visual_z_range_render_state_policy},
    {"visual_ds_smaller_than_rt_policy",
            test_visual_ds_smaller_than_rt_policy},
    {"visual_depth_buffer_clear_policy",
            test_visual_depth_buffer_clear_policy},
    {"visual_depth_buffer_reset_policy",
            test_visual_depth_buffer_reset_policy},
    {"visual_depth_bounds_caps_policy",
            test_visual_depth_bounds_caps_policy},
    {"visual_zenable_render_state_policy",
            test_visual_zenable_render_state_policy},
    {"visual_zwriteenable_render_state_policy",
            test_visual_zwriteenable_render_state_policy},
    {"visual_multisampled_depth_buffer_caps_policy",
            test_visual_multisampled_depth_buffer_caps_policy},
    {"visual_depth_clamp_render_state_policy",
            test_visual_depth_clamp_render_state_policy},
    {"visual_clear_color_only_policy",
            test_visual_clear_color_only_policy},
    {"visual_clear_smaller_rt_policy",
            test_visual_clear_smaller_rt_policy},
    {"visual_colorfill_format_policy",
            test_visual_colorfill_format_policy},
    {"visual_offscreen_surface_creation_policy",
            test_visual_offscreen_surface_creation_policy},
    {"visual_stencil_cull_caps_policy",
            test_visual_stencil_cull_caps_policy},
    {"visual_update_surface_policy",
            test_visual_update_surface_policy},
    {"visual_swapchain_flip_present_policy",
            test_visual_swapchain_flip_present_policy},
    {"visual_shademode_render_state_policy",
            test_visual_shademode_render_state_policy},
    {"visual_lighting_render_state_policy",
            test_visual_lighting_render_state_policy},
    {"visual_lighting_world_view_matrix_policy",
            test_visual_lighting_world_view_matrix_policy},
    {"visual_release_buffer_bound_policy",
            test_visual_release_buffer_bound_policy},
    {"visual_evict_managed_resources_policy",
            test_visual_evict_managed_resources_policy},
    {"visual_add_dirty_rect_policy",
            test_visual_add_dirty_rect_policy},
    {"visual_multisample_get_front_buffer_data_policy",
            test_visual_multisample_get_front_buffer_data_policy},
    {"visual_multisample_rt_ds_mismatch_policy",
            test_visual_multisample_rt_ds_mismatch_policy},
    {"visual_buffer_no_dirty_update_policy",
            test_visual_buffer_no_dirty_update_policy},
    {"visual_yuv_color_caps_policy",
            test_visual_yuv_color_caps_policy},
    {"visual_yuv_layout_lock_policy",
            test_visual_yuv_layout_lock_policy},
    {"visual_3dc_format_caps_policy",
            test_visual_3dc_format_caps_policy},
    {"visual_position_index_decl_policy",
            test_visual_position_index_decl_policy},
    {"visual_mvp_software_vp_policy",
            test_visual_mvp_software_vp_policy},
    {"state_management_all_capture_apply_matrix",
            test_state_management_all_capture_apply_matrix},
    {"state_management_pixel_capture_apply_slice",
            test_state_management_pixel_capture_apply_slice},
    {"state_management_vertex_capture_apply_slice",
            test_state_management_vertex_capture_apply_slice},
    {"query_get_data_size_policy",
            test_query_get_data_size_policy},
    {"check_device_format_conversion_matrix",
            test_check_device_format_conversion_matrix},
    {"multithreaded_device_creation_policy",
            test_multithreaded_device_creation_policy},
    {"visual_shadow_depth_compare_caps_policy",
            test_visual_shadow_depth_compare_caps_policy},
    {"visual_filling_convention_caps_policy",
            test_visual_filling_convention_caps_policy},
    {"visual_line_antialiasing_blending_state_policy",
            test_visual_line_antialiasing_blending_state_policy},
    {"visual_blit_format_conversion_policy",
            test_visual_blit_format_conversion_policy},
    {"visual_specular_lighting_render_state_policy",
            test_visual_specular_lighting_render_state_policy},
    {"visual_max_index16_draw_policy",
            test_visual_max_index16_draw_policy},
    {"visual_null_format_caps_policy",
            test_visual_null_format_caps_policy},
    {"visual_sample_mask_render_state_policy",
            test_visual_sample_mask_render_state_policy},
    {"visual_depth_stencil_init_policy",
            test_visual_depth_stencil_init_policy},
    {"vendor_policy_texbem_unsupported",
            test_vendor_policy_texbem_unsupported},
    {"vendor_policy_texdepth_unsupported",
            test_vendor_policy_texdepth_unsupported},
    {"vendor_policy_intz_caps", test_vendor_policy_intz_caps},
    {"vendor_policy_fetch4_caps", test_vendor_policy_fetch4_caps},
    {"vendor_policy_resz_caps", test_vendor_policy_resz_caps},
    {"vendor_policy_mipmap_upload_policy",
            test_vendor_policy_mipmap_upload_policy},
    {"miptree_layout_lock_pitch_policy",
            test_miptree_layout_lock_pitch_policy},
    {"visual_bumpenvmap_tss_policy", test_visual_bumpenvmap_tss_policy},
    {"visual_pretransformed_vertex_declaration_policy",
            test_visual_pretransformed_vertex_declaration_policy},
    {"visual_vface_pixel_shader_create_policy",
            test_visual_vface_pixel_shader_create_policy},
    {"visual_fp_special_caps_policy", test_visual_fp_special_caps_policy},
};

int main(void)
{
    struct d3d9_api api;
    unsigned int i;

    if (!load_d3d9_api(&api))
        return 77;

    for (i = 0; i < sizeof(tests) / sizeof(tests[0]); ++i)
    {
        unsigned int failures_before = checks_failed;

        current_test = tests[i].name;
        printf("RUN  [%s]\n", current_test);
        tests[i].func(&api);
        pump_window_messages();
        printf("%s [%s]\n", checks_failed == failures_before ? "PASS" : "FAIL",
                current_test);
    }

    printf("SUMMARY checks=%u failures=%u skips=%u\n",
            checks_run, checks_failed, tests_skipped);

    if (api.module)
        FreeLibrary(api.module);

    return checks_failed ? 1 : 0;
}
