#!/usr/bin/env python3
import os
import re
import subprocess
import sys


COUNTER_RE = re.compile(r"\b([a-zA-Z0-9_]+)=([^\s]+)")
PERF_PREFIX = "[dxmt9-perf] "


def fail(message: str) -> int:
    print(f"assert_perf_counters.py: {message}", file=sys.stderr)
    return 1


def main() -> int:
    if len(sys.argv) < 2:
        return fail("usage: assert_perf_counters.py <executable>")

    env = os.environ.copy()
    env["DXMT_PERF_COUNTERS"] = "1"
    result = subprocess.run(
        sys.argv[1:],
        env=env,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    if result.returncode != 0:
        sys.stdout.write(result.stdout)
        sys.stderr.write(result.stderr)
        return result.returncode

    perf_lines = [
        line for line in result.stderr.splitlines() if line.startswith(PERF_PREFIX)
    ]
    if len(perf_lines) != 1:
        return fail(f"expected one {PERF_PREFIX!r} line, got {len(perf_lines)}")

    counters = dict(COUNTER_RE.findall(perf_lines[0]))
    expected = {
        "metal_buffers": "2",
        "metal_buffer_bytes": "768",
        "draw_geometry_samples": "1",
        "draw_geometry_ffp": "1",
        "draw_geometry_vs": "0",
        "draw_geometry_indexed": "1",
        "draw_geometry_index16": "1",
        "draw_geometry_index32": "0",
        "draw_geometry_direct": "0",
        "draw_geometry_up": "1",
        "draw_geometry_expanded": "0",
        "draw_geometry_nonzero_base_vertex": "1",
        "draw_geometry_nonzero_start_index": "1",
        "draw_geometry_nonzero_stream0_offset": "1",
        "draw_geometry_last_stream0_stride": "32",
        "draw_geometry_last_decl_hash": "0x1234",
        "uniform_vs_consts_calls": "0",
        "uniform_vs_consts_bytes": "0",
        "uniform_ps_consts_calls": "0",
        "uniform_ps_consts_bytes": "0",
        "uniform_ffp_vs_calls": "0",
        "uniform_ffp_vs_bytes": "0",
        "uniform_ffp_ps_calls": "0",
        "uniform_ffp_ps_bytes": "0",
        "uniform_volatile_pushes": "0",
        "chunk_admit": "0",
        "chunk_reject": "0",
        "ring_arena_heap_fallback_count": "0",
        "ring_arena_heap_fallback_bytes": "0",
        "ring_arena_heap_fallback_argbuf": "0",
        "ring_arena_heap_fallback_lambda": "0",
        "ring_arena_heap_fallback_staging": "0",
        "ring_arena_heap_fallback_copytemp": "0",
        "render_pass_load_action_load": "0",
        "render_pass_load_action_clear": "0",
        "render_pass_load_action_dontcare": "0",
        "render_pass_load_action_depth_load": "0",
        "render_pass_load_action_depth_clear": "0",
        "render_pass_load_action_depth_dontcare": "0",
        "render_pass_load_action_stencil_load": "0",
        "render_pass_load_action_stencil_clear": "0",
        "render_pass_load_action_stencil_dontcare": "0",
        "render_pass_store_action_store": "0",
        "render_pass_store_action_dontcare": "0",
        "render_pass_store_action_resolve": "0",
        "render_pass_store_action_depth_store": "0",
        "render_pass_store_action_depth_dontcare": "0",
        "render_pass_store_action_stencil_store": "0",
        "render_pass_store_action_stencil_dontcare": "0",
        "render_pass_tile_preservation_bytes": "0",
    }
    for key, value in expected.items():
        actual = counters.get(key)
        if actual != value:
            return fail(f"expected {key}={value}, got {actual!r}")

    # encodeDraw() sub-phase CPU timers must always be emitted so that downstream
    # parsers can consume them; the allocation-counter spec exercises no real
    # encodeDraw path, so these are presence-only checks (exact ms is non-deterministic).
    sub_phase_keys = (
        "encode_draw_pipeline_lookup_cpu_ms",
        "encode_draw_pipeline_lookup_cpu_max_ms",
        "encode_draw_uniform_build_cpu_ms",
        "encode_draw_uniform_build_cpu_max_ms",
        "encode_draw_fvf_decode_cpu_ms",
        "encode_draw_fvf_decode_cpu_max_ms",
        "encode_draw_binding_packet_cpu_ms",
        "encode_draw_binding_packet_plan_cpu_ms",
        "encode_draw_binding_packet_cache_cpu_ms",
        "encode_draw_binding_packet_cache_key_cpu_ms",
        "encode_draw_binding_packet_cache_hash_cpu_ms",
        "encode_draw_binding_packet_cache_probe_cpu_ms",
        "encode_draw_binding_packet_cache_store_cpu_ms",
        "encode_draw_binding_packet_cache_hits",
        "encode_draw_binding_packet_cache_misses",
        "encode_draw_binding_packet_cache_collisions",
        "encode_draw_binding_packet_texture_record_cpu_ms",
        "encode_draw_argbuf_setup_cpu_ms",
        "encode_draw_argbuf_open_cpu_ms",
        "encode_draw_argbuf_open_call_cpu_ms",
        "encode_draw_argbuf_reopen_post_cpu_ms",
        "encode_draw_argbuf_reopen_table_probe_cpu_ms",
        "encode_draw_argbuf_reopen_table_shadow_store_cpu_ms",
        "encode_draw_argbuf_reopen_byte_account_cpu_ms",
        "encode_draw_argbuf_reopen_cbuf_cache_probe_cpu_ms",
        "encode_draw_argbuf_reopen_cbuf_dirty_scan_cpu_ms",
        "encode_draw_argbuf_reopen_cbuf_force_dirty_cpu_ms",
        "encode_draw_argbuf_open_reserve_cpu_ms",
        "encode_draw_argbuf_open_set_argument_buffer_cpu_ms",
        "encode_draw_argbuf_table_bind_cpu_ms",
        "encode_draw_argbuf_table_bind_calls",
        "encode_draw_argbuf_table_bind_skipped",
        "encode_draw_argbuf_cbuf_update_cpu_ms",
        "encode_draw_argbuf_cbuf_build_cpu_ms",
        "encode_draw_argbuf_cbuf_upload_cpu_ms",
        "encode_draw_argbuf_cbuf_setbuffer_cpu_ms",
        "encode_draw_argbuf_cbuf_build_vs_cpu_ms",
        "encode_draw_argbuf_cbuf_build_ps_cpu_ms",
        "encode_draw_argbuf_cbuf_build_ffp_vs_cpu_ms",
        "encode_draw_argbuf_cbuf_build_ffp_ps_cpu_ms",
        "encode_draw_argbuf_cbuf_upload_vs_cpu_ms",
        "encode_draw_argbuf_cbuf_upload_ps_cpu_ms",
        "encode_draw_argbuf_cbuf_upload_ffp_vs_cpu_ms",
        "encode_draw_argbuf_cbuf_upload_ffp_ps_cpu_ms",
        "encode_draw_argbuf_cbuf_setbuffer_vs_cpu_ms",
        "encode_draw_argbuf_cbuf_setbuffer_ps_cpu_ms",
        "encode_draw_argbuf_cbuf_setbuffer_ffp_vs_cpu_ms",
        "encode_draw_argbuf_cbuf_setbuffer_ffp_ps_cpu_ms",
        "encode_draw_argbuf_cbuf_upload_plan_cpu_ms",
        "encode_draw_argbuf_cbuf_upload_plan_vs_cpu_ms",
        "encode_draw_argbuf_cbuf_upload_plan_ps_cpu_ms",
        "encode_draw_argbuf_cbuf_binding_hash_cpu_ms",
        "encode_draw_argbuf_cbuf_binding_hash_vs_cpu_ms",
        "encode_draw_argbuf_cbuf_binding_hash_ps_cpu_ms",
        "encode_draw_argbuf_cbuf_binding_hash_ffp_vs_cpu_ms",
        "encode_draw_argbuf_cbuf_binding_hash_ffp_ps_cpu_ms",
        "encode_draw_argbuf_cbuf_binding_write_cpu_ms",
        "encode_draw_argbuf_cbuf_binding_write_vs_cpu_ms",
        "encode_draw_argbuf_cbuf_binding_write_ps_cpu_ms",
        "encode_draw_argbuf_cbuf_binding_write_ffp_vs_cpu_ms",
        "encode_draw_argbuf_cbuf_binding_write_ffp_ps_cpu_ms",
        "encode_draw_argbuf_cbuf_observer_cpu_ms",
        "encode_draw_argbuf_cbuf_observer_vs_cpu_ms",
        "encode_draw_argbuf_cbuf_observer_ps_cpu_ms",
        "encode_draw_argbuf_cbuf_observer_ffp_vs_cpu_ms",
        "encode_draw_argbuf_cbuf_observer_ffp_ps_cpu_ms",
        "d3d9_snapshot_cache_lookup_cpu_ms",
        "d3d9_snapshot_cache_hit_cpu_ms",
        "d3d9_snapshot_cache_miss_cpu_ms",
        "d3d9_snapshot_cache_direct_hit_cpu_ms",
        "d3d9_snapshot_cache_direct_miss_cpu_ms",
        "d3d9_snapshot_cache_batch_hit_cpu_ms",
        "d3d9_snapshot_cache_batch_miss_cpu_ms",
        "d3d9_snapshot_cache_binding_layout_cpu_ms",
        "d3d9_snapshot_cache_uniform_refresh_cpu_ms",
        "d3d9_snapshot_cache_uniform_build_cpu_ms",
        "d3d9_snapshot_cache_uniform_hash_cpu_ms",
        "d3d9_snapshot_cache_miss_shader_layout_cpu_ms",
        "d3d9_snapshot_cache_miss_uniform_build_cpu_ms",
        "d3d9_snapshot_cache_miss_hot_build_cpu_ms",
        "d3d9_snapshot_cache_direct_miss_shader_layout_cpu_ms",
        "d3d9_snapshot_cache_direct_miss_uniform_build_cpu_ms",
        "d3d9_snapshot_cache_direct_miss_hot_build_cpu_ms",
        "d3d9_snapshot_cache_batch_miss_shader_layout_cpu_ms",
        "d3d9_snapshot_cache_batch_miss_uniform_build_cpu_ms",
        "d3d9_snapshot_cache_batch_miss_hot_build_cpu_ms",
        "d3d9_snapshot_cache_batch_miss_hot_build_zero_init_cpu_ms",
        "d3d9_snapshot_cache_batch_miss_hot_build_key_cpu_ms",
        "d3d9_snapshot_cache_batch_miss_hot_build_key_zero_init_cpu_ms",
        "d3d9_snapshot_cache_batch_miss_hot_build_key_stream_cpu_ms",
        "d3d9_snapshot_cache_batch_miss_hot_build_key_shader_cpu_ms",
        "d3d9_snapshot_cache_batch_miss_hot_build_key_constant_cpu_ms",
        "d3d9_snapshot_cache_batch_miss_hot_build_key_texture_cpu_ms",
        "d3d9_snapshot_cache_batch_miss_hot_build_key_sampler_cpu_ms",
        "d3d9_snapshot_cache_batch_miss_hot_build_key_render_state_cpu_ms",
        "d3d9_snapshot_cache_batch_miss_hot_build_key_attachment_cpu_ms",
        "d3d9_snapshot_cache_batch_miss_hot_build_key_uniform_cpu_ms",
        "d3d9_snapshot_cache_batch_miss_hot_build_binding_copy_cpu_ms",
        "d3d9_snapshot_cache_batch_miss_hot_build_render_state_cpu_ms",
        "d3d9_snapshot_cache_batch_miss_hot_build_texture_stage_state_cpu_ms",
        "d3d9_snapshot_cache_batch_miss_hot_build_sampler_state_cpu_ms",
        "d3d9_snapshot_cache_batch_miss_hot_build_tail_copy_cpu_ms",
        "d3d9_snapshot_cache_batch_miss_hot_build_flat_render_reuse_hits",
        "d3d9_snapshot_cache_batch_miss_hot_build_flat_render_reuse_misses",
        "d3d9_snapshot_cache_batch_miss_hot_build_flat_tss_reuse_hits",
        "d3d9_snapshot_cache_batch_miss_hot_build_flat_tss_reuse_misses",
        "d3d9_snapshot_cache_batch_miss_hot_build_flat_sampler_reuse_hits",
        "d3d9_snapshot_cache_batch_miss_hot_build_flat_sampler_reuse_misses",
        "d3d9_snapshot_cache_batch_miss_uniform_nonconst_hash_reuse_hits",
        "d3d9_snapshot_cache_batch_miss_uniform_nonconst_hash_reuse_misses",
        "d3d9_snapshot_cache_batch_miss_uniform_build_calls",
        "d3d9_snapshot_cache_batch_miss_uniform_build_vs_const_copy_cpu_ms",
        "d3d9_snapshot_cache_batch_miss_uniform_build_ps_const_copy_cpu_ms",
        "d3d9_snapshot_cache_batch_miss_uniform_build_ffp_matrix_cpu_ms",
        "d3d9_snapshot_cache_batch_miss_uniform_build_ffp_material_light_cpu_ms",
        "d3d9_snapshot_cache_batch_miss_uniform_build_texture_transform_cpu_ms",
        "d3d9_snapshot_cache_batch_miss_uniform_build_clip_plane_cpu_ms",
        "d3d9_snapshot_cache_batch_miss_uniform_build_hash_cpu_ms",
        "d3d9_snapshot_cache_batch_miss_uniform_build_vs_const_hash_cpu_ms",
        "d3d9_snapshot_cache_batch_miss_uniform_build_ps_const_hash_cpu_ms",
        "d3d9_snapshot_cache_batch_miss_uniform_build_nonconst_hash_cpu_ms",
        "d3d9_snapshot_cache_batch_miss_uniform_build_nonconst_hash_world_view_proj_cpu_ms",
        "d3d9_snapshot_cache_batch_miss_uniform_build_nonconst_hash_ffp_world_view_cpu_ms",
        "d3d9_snapshot_cache_batch_miss_uniform_build_nonconst_hash_ffp_normal_matrix_cpu_ms",
        "d3d9_snapshot_cache_batch_miss_uniform_build_nonconst_hash_material_cpu_ms",
        "d3d9_snapshot_cache_batch_miss_uniform_build_nonconst_hash_lights_cpu_ms",
        "d3d9_snapshot_cache_batch_miss_uniform_build_nonconst_hash_ffp_blend_wvp_cpu_ms",
        "d3d9_snapshot_cache_batch_miss_uniform_build_nonconst_hash_texture_transforms_cpu_ms",
        "d3d9_snapshot_cache_batch_miss_uniform_build_nonconst_hash_clip_planes_cpu_ms",
        "d3d9_snapshot_cache_batch_miss_uniform_build_payload_combine_hash_cpu_ms",
        "d3d9_snapshot_cache_batch_miss_uniform_build_vs_const_hash_full",
        "d3d9_snapshot_cache_batch_miss_uniform_build_ps_const_hash_full",
        "d3d9_snapshot_cache_batch_miss_uniform_build_vs_const_hash_full_no_usage",
        "d3d9_snapshot_cache_batch_miss_uniform_build_ps_const_hash_full_no_usage",
        "d3d9_snapshot_cache_batch_miss_uniform_build_vs_const_hash_full_unknown",
        "d3d9_snapshot_cache_batch_miss_uniform_build_ps_const_hash_full_unknown",
        "d3d9_snapshot_cache_batch_miss_uniform_build_vs_const_hash_full_unknown_bytecode",
        "d3d9_snapshot_cache_batch_miss_uniform_build_ps_const_hash_full_unknown_bytecode",
        "d3d9_snapshot_cache_batch_miss_uniform_build_vs_const_hash_full_unknown_non_bytecode",
        "d3d9_snapshot_cache_batch_miss_uniform_build_ps_const_hash_full_unknown_non_bytecode",
        "d3d9_snapshot_cache_batch_miss_uniform_build_vs_const_hash_full_indexed_float",
        "d3d9_snapshot_cache_batch_miss_uniform_build_vs_const_hash_full_indexed_float_min_safe_bytes",
        "d3d9_snapshot_cache_batch_miss_uniform_build_vs_const_hash_full_indexed_float_potential_saved_bytes",
        "d3d9_snapshot_cache_batch_miss_uniform_build_ps_const_hash_full_indexed_float",
        "d3d9_snapshot_cache_batch_miss_uniform_build_vs_const_hash_full_indexed_int",
        "d3d9_snapshot_cache_batch_miss_uniform_build_ps_const_hash_full_indexed_int",
        "d3d9_snapshot_cache_batch_miss_uniform_build_vs_const_hash_full_indexed_bool",
        "d3d9_snapshot_cache_batch_miss_uniform_build_ps_const_hash_full_indexed_bool",
        "d3d9_snapshot_cache_batch_miss_uniform_build_vs_const_hash_bytes",
        "d3d9_snapshot_cache_batch_miss_uniform_build_ps_const_hash_bytes",
        "d3d9_snapshot_uniform_build_calls",
        "d3d9_snapshot_uniform_build_vs_const_copy_cpu_ms",
        "d3d9_snapshot_uniform_build_ps_const_copy_cpu_ms",
        "d3d9_snapshot_uniform_build_ffp_matrix_cpu_ms",
        "d3d9_snapshot_uniform_build_ffp_material_light_cpu_ms",
        "d3d9_snapshot_uniform_build_texture_transform_cpu_ms",
        "d3d9_snapshot_uniform_build_clip_plane_cpu_ms",
        "d3d9_snapshot_uniform_build_hash_cpu_ms",
        "d3d9_snapshot_uniform_build_vs_const_hash_cpu_ms",
        "d3d9_snapshot_uniform_build_ps_const_hash_cpu_ms",
        "d3d9_snapshot_uniform_build_nonconst_hash_cpu_ms",
        "d3d9_snapshot_uniform_build_nonconst_hash_world_view_proj_cpu_ms",
        "d3d9_snapshot_uniform_build_nonconst_hash_ffp_world_view_cpu_ms",
        "d3d9_snapshot_uniform_build_nonconst_hash_ffp_normal_matrix_cpu_ms",
        "d3d9_snapshot_uniform_build_nonconst_hash_material_cpu_ms",
        "d3d9_snapshot_uniform_build_nonconst_hash_lights_cpu_ms",
        "d3d9_snapshot_uniform_build_nonconst_hash_ffp_blend_wvp_cpu_ms",
        "d3d9_snapshot_uniform_build_nonconst_hash_texture_transforms_cpu_ms",
        "d3d9_snapshot_uniform_build_nonconst_hash_clip_planes_cpu_ms",
        "d3d9_snapshot_uniform_build_payload_combine_hash_cpu_ms",
        "d3d9_snapshot_uniform_build_vs_const_hash_full",
        "d3d9_snapshot_uniform_build_ps_const_hash_full",
        "d3d9_snapshot_uniform_build_vs_const_hash_full_no_usage",
        "d3d9_snapshot_uniform_build_ps_const_hash_full_no_usage",
        "d3d9_snapshot_uniform_build_vs_const_hash_full_unknown",
        "d3d9_snapshot_uniform_build_ps_const_hash_full_unknown",
        "d3d9_snapshot_uniform_build_vs_const_hash_full_unknown_bytecode",
        "d3d9_snapshot_uniform_build_ps_const_hash_full_unknown_bytecode",
        "d3d9_snapshot_uniform_build_vs_const_hash_full_unknown_non_bytecode",
        "d3d9_snapshot_uniform_build_ps_const_hash_full_unknown_non_bytecode",
        "d3d9_snapshot_uniform_build_vs_const_hash_full_indexed_float",
        "d3d9_snapshot_uniform_build_vs_const_hash_full_indexed_float_min_safe_bytes",
        "d3d9_snapshot_uniform_build_vs_const_hash_full_indexed_float_potential_saved_bytes",
        "d3d9_snapshot_uniform_build_ps_const_hash_full_indexed_float",
        "d3d9_snapshot_uniform_build_vs_const_hash_full_indexed_int",
        "d3d9_snapshot_uniform_build_ps_const_hash_full_indexed_int",
        "d3d9_snapshot_uniform_build_vs_const_hash_full_indexed_bool",
        "d3d9_snapshot_uniform_build_ps_const_hash_full_indexed_bool",
        "d3d9_snapshot_uniform_build_vs_const_hash_bytes",
        "d3d9_snapshot_uniform_build_ps_const_hash_bytes",
        "d3d9_snapshot_uniform_copy_cpu_ms",
        "d3d9_snapshot_uniform_materialized",
        "d3d9_snapshot_uniform_materialized_bytes",
        "d3d9_snapshot_uniform_elided",
        "d3d9_snapshot_uniform_elided_bytes",
        "d3d9_snapshot_uniform_adjacent_same_generation",
        "d3d9_snapshot_uniform_adjacent_same_generation_bytes",
        "d3d9_snapshot_uniform_adjacent_same_generation_same_state_lane",
        "d3d9_snapshot_uniform_adjacent_same_generation_same_state_lane_bytes",
        "d3d9_snapshot_uniform_adjacent_same_generation_diff_state_lane",
        "d3d9_snapshot_uniform_adjacent_same_generation_diff_state_lane_bytes",
        "d3d9_snapshot_uniform_adjacent_same_payload_hash",
        "d3d9_snapshot_uniform_adjacent_same_payload_hash_bytes",
        "d3d9_snapshot_uniform_adjacent_same_payload_hash_same_state_lane",
        "d3d9_snapshot_uniform_adjacent_same_payload_hash_same_state_lane_bytes",
        "d3d9_snapshot_uniform_adjacent_same_payload_hash_diff_state_lane",
        "d3d9_snapshot_uniform_adjacent_same_payload_hash_diff_state_lane_bytes",
        "d3d9_snapshot_uniform_adjacent_same_payload_hash_diff_generation",
        "d3d9_snapshot_uniform_adjacent_same_payload_hash_diff_generation_bytes",
        "d3d9_snapshot_uniform_adjacent_previous_payload",
        "d3d9_snapshot_uniform_adjacent_same_vs_const_hash",
        "d3d9_snapshot_uniform_adjacent_same_vs_const_hash_same_state_lane",
        "d3d9_snapshot_uniform_adjacent_same_vs_const_hash_diff_generation",
        "d3d9_snapshot_uniform_adjacent_same_ps_const_hash",
        "d3d9_snapshot_uniform_adjacent_same_ps_const_hash_same_state_lane",
        "d3d9_snapshot_uniform_adjacent_same_ps_const_hash_diff_generation",
        "d3d9_snapshot_uniform_adjacent_same_shader_const_hashes",
        "d3d9_snapshot_uniform_adjacent_same_shader_const_hashes_same_state_lane",
        "d3d9_snapshot_uniform_adjacent_same_shader_const_hashes_diff_generation",
        "d3d9_snapshot_uniform_adjacent_same_fixed_payload_hash",
        "d3d9_snapshot_uniform_adjacent_same_fixed_payload_hash_same_state_lane",
        "d3d9_snapshot_uniform_adjacent_same_fixed_payload_hash_diff_generation",
        "d3d9_snapshot_uniform_adjacent_same_fixed_and_shader_const_hashes",
        "d3d9_snapshot_uniform_adjacent_same_fixed_and_shader_const_hashes_same_state_lane",
        "d3d9_snapshot_uniform_adjacent_same_fixed_and_shader_const_hashes_diff_generation",
        "d3d9_snapshot_state_copy_cpu_ms",
        "d3d9_snapshot_debug_snapshot_cpu_ms",
        "d3d9_snapshot_binding_override_cpu_ms",
        "d3d9_snapshot_binding_override_stream_scans",
        "d3d9_snapshot_binding_override_stream_records",
        "d3d9_snapshot_binding_override_index_records",
        "draw_uniform_payload_lookup_candidate_hits",
        "draw_uniform_payload_lookup_last_hits",
        "draw_uniform_payload_lookup_bucket_hits",
        "draw_uniform_payload_lookup_bucket_misses",
        "draw_uniform_payload_lookup_linear_hits",
        "draw_uniform_payload_lookup_bucket_probes",
        "draw_uniform_payload_lookup_bucket_collisions",
        "draw_uniform_payload_lookup_hash_collisions",
        "draw_uniform_payload_lookup_semantic_hash_misses",
        "draw_uniform_payload_lookup_semantic_hash_miss_bytes",
        "draw_uniform_payload_lookup_cpu_ms",
        "draw_uniform_payload_lookup_cpu_max_ms",
        "draw_uniform_payload_lookup_bucket_cpu_ms",
        "draw_uniform_payload_lookup_bucket_cpu_max_ms",
        "draw_uniform_payload_appends",
        "draw_uniform_payload_append_bytes",
        "draw_uniform_fixed_payload_appends",
        "draw_uniform_fixed_payload_append_bytes",
        "draw_uniform_payload_append_reserve_cpu_ms",
        "draw_uniform_payload_append_reserve_cpu_max_ms",
        "draw_uniform_payload_append_copy_cpu_ms",
        "draw_uniform_payload_append_copy_cpu_max_ms",
        "draw_uniform_payload_append_link_cpu_ms",
        "draw_uniform_payload_append_link_cpu_max_ms",
        "submit_draw_run_batch_discarded_state_records",
        "submit_draw_run_batch_discarded_state_bytes",
        "encode_draw_argbuf_cbuf_cache_merge_cpu_ms",
        "encode_draw_argbuf_cbuf_cached_repoint_cpu_ms",
        "encode_draw_argbuf_cbuf_full_repoint_cpu_ms",
        "encode_draw_argbuf_cbuf_content_probe_cpu_ms",
        "encode_draw_argbuf_cbuf_update_vs_cpu_ms",
        "encode_draw_argbuf_cbuf_update_ps_cpu_ms",
        "encode_draw_argbuf_cbuf_update_ffp_vs_cpu_ms",
        "encode_draw_argbuf_cbuf_update_ffp_ps_cpu_ms",
        "encode_draw_stream_bind_cpu_ms",
        "encode_draw_stream_bind_cpu_max_ms",
        "encode_draw_stream_bind_raster_phase_cpu_ms",
        "encode_draw_stream_bind_raster_phase_calls",
        "encode_draw_stream_bind_ffp_stream_cpu_ms",
        "encode_draw_stream_bind_ffp_stream_calls",
        "encode_draw_stream_bind_shader_stream_cpu_ms",
        "encode_draw_stream_bind_shader_stream_calls",
        "encode_draw_stream_bind_texture_phase_cpu_ms",
        "encode_draw_stream_bind_texture_phase_calls",
        "encode_draw_stream_bind_index_phase_cpu_ms",
        "encode_draw_stream_bind_index_phase_calls",
        "encode_draw_texture_sampler_fragment_resolve_cpu_ms",
        "encode_draw_texture_sampler_fragment_resolve_calls",
        "encode_draw_texture_sampler_fragment_resolve_texture_cpu_ms",
        "encode_draw_texture_sampler_fragment_resolve_texture_calls",
        "encode_draw_texture_sampler_fragment_resource_array_cpu_ms",
        "encode_draw_texture_sampler_fragment_resource_array_calls",
        "encode_draw_texture_sampler_fragment_direct_cpu_ms",
        "encode_draw_texture_sampler_fragment_direct_calls",
        "encode_draw_texture_sampler_fragment_direct_texture_cpu_ms",
        "encode_draw_texture_sampler_fragment_direct_texture_calls",
        "encode_draw_texture_sampler_fragment_direct_texture_set_cpu_ms",
        "encode_draw_texture_sampler_fragment_direct_texture_set_calls",
        "encode_draw_texture_sampler_fragment_direct_sampler_cpu_ms",
        "encode_draw_texture_sampler_fragment_direct_sampler_calls",
        "encode_draw_texture_sampler_fragment_direct_sampler_set_cpu_ms",
        "encode_draw_texture_sampler_fragment_direct_sampler_set_calls",
        "encode_draw_texture_sampler_sampler_lookup_cpu_ms",
        "encode_draw_texture_sampler_sampler_lookup_calls",
        "encode_draw_texture_sampler_sampler_lookup_skipped_prehandle",
        "encode_draw_texture_sampler_lod_bias_cpu_ms",
        "encode_draw_texture_sampler_lod_bias_calls",
        "encode_draw_texture_sampler_vertex_resolve_cpu_ms",
        "encode_draw_texture_sampler_vertex_resolve_calls",
        "encode_draw_texture_sampler_vertex_direct_cpu_ms",
        "encode_draw_texture_sampler_vertex_direct_calls",
        "encode_draw_issue_cpu_ms",
        "encode_draw_issue_cpu_max_ms",
    )
    for key in sub_phase_keys:
        if key not in counters:
            return fail(f"expected key {key} present in [dxmt9-perf] line")

    sys.stdout.write(result.stdout)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
