#!/usr/bin/env python3
"""Generate the bounded lifecycle vocabulary used by the CPU pipeline model.

The table is intentionally a vocabulary/shape contract.  The C++ predicates
remain the executable policy; this generated module prevents the model from
silently losing a production owner or a terminal disposition.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import re

TABLE_HEADER = Path(__file__).parents[2] / "src/dxmt9/dxmt9_pipeline_lifecycle.hpp"


def read_rows() -> tuple[tuple[str, ...], ...]:
    source = TABLE_HEADER.read_text()
    match = re.search(
        r"#define DXMT9_PIPELINE_LIFECYCLE_ROWS\(X\)(.*?)(?=\n\s*struct PipelineLifecycleRow)",
        source,
        re.DOTALL,
    )
    if not match:
        raise RuntimeError(f"lifecycle table macro not found in {TABLE_HEADER}")
    rows = tuple(
        tuple(value.strip() for value in row)
        for row in re.findall(r"\bX\(([^)]*)\)", match.group(1))
        for row in (row.split(","),)
        if len(row) == 5
    )
    if not rows:
        raise RuntimeError(f"lifecycle table macro is empty in {TABLE_HEADER}")
    return rows


def render(rows: tuple[tuple[str, ...], ...]) -> str:
    lines = [
        "---- MODULE PipelineLifecycleTable ----",
        "(* Generated by scripts/check/gen_pipeline_lifecycle_table.py. *)",
        "",
        "LifecycleRows == {",
    ]
    for index, row in enumerate(rows):
        lines.append(
            '  [from |-> "{}", to |-> "{}", owner |-> "{}", '
            'disposition |-> "{}", control |-> "{}"]{}'.format(
                *row, "," if index + 1 < len(rows) else "")
        )
    lines.extend(
        [
            "}",
            "",
            "LifecycleRow(from, to, owner, disposition, control) ==",
            "  [from |-> from, to |-> to, owner |-> owner,",
            "   disposition |-> disposition, control |-> control]",
            "",
            "KnownLifecycleRow(from, to, owner, disposition, control) ==",
            "  LifecycleRow(from, to, owner, disposition, control)\\in LifecycleRows",
            "",
            "Owners == {row.owner : row \\in LifecycleRows}",
            "Controls == {row.control : row \\in LifecycleRows}",
            "DispositionNames == {row.disposition : row \\in LifecycleRows}",
            "",
            "====",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--output", type=Path,
                        default=Path(__file__).parents[2] /
                        "specs/verification/tla/PipelineLifecycleTable.tla")
    args = parser.parse_args()
    expected = render(read_rows())
    if args.check:
        return int(not args.output.exists() or args.output.read_text() != expected)
    args.output.write_text(expected)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
