---- MODULE PipelineLifecycleTable ----
(* Generated by scripts/check/gen_pipeline_lifecycle_table.py. *)

LifecycleRows == {
  [from |-> "SourceArrival", to |-> "ProducerOwned", owner |-> "PeImport", disposition |-> "Advance", control |-> "Normal"],
  [from |-> "ProducerOwned", to |-> "RawOwned", owner |-> "Replay", disposition |-> "Advance", control |-> "Normal"],
  [from |-> "RawOwned", to |-> "ReplayBorrowed", owner |-> "Replay", disposition |-> "Advance", control |-> "Normal"],
  [from |-> "RawOwned", to |-> "RawOwned", owner |-> "Queue", disposition |-> "AdmissionWait", control |-> "Normal"],
  [from |-> "RawOwned", to |-> "ReplayBorrowed", owner |-> "Replay", disposition |-> "AdmissionRetry", control |-> "Normal"],
  [from |-> "ReplayBorrowed", to |-> "ReplayBorrowed", owner |-> "Replay", disposition |-> "BuildProgress", control |-> "Normal"],
  [from |-> "ReplayBorrowed", to |-> "ReplayBorrowed", owner |-> "Replay", disposition |-> "Advance", control |-> "Normal"],
  [from |-> "ReplayBorrowed", to |-> "FinalOwned", owner |-> "DirectPublication", disposition |-> "Advance", control |-> "Normal"],
  [from |-> "ReplayBorrowed", to |-> "FinalOwned", owner |-> "LegacyPublication", disposition |-> "Advance", control |-> "Normal"],
  [from |-> "ReplayBorrowed", to |-> "FinalOwned", owner |-> "Queue", disposition |-> "Advance", control |-> "Normal"],
  [from |-> "FinalOwned", to |-> "Encoding", owner |-> "SerialEncode", disposition |-> "Advance", control |-> "Normal"],
  [from |-> "FinalOwned", to |-> "Encoding", owner |-> "SelectedParallel", disposition |-> "Advance", control |-> "Normal"],
  [from |-> "FinalOwned", to |-> "Encoding", owner |-> "Queue", disposition |-> "Advance", control |-> "Normal"],
  [from |-> "Encoding", to |-> "Encoding", owner |-> "Queue", disposition |-> "ChildJoin", control |-> "Normal"],
  [from |-> "Encoding", to |-> "Encoding", owner |-> "SelectedParallel", disposition |-> "ChildJoin", control |-> "Normal"],
  [from |-> "Encoding", to |-> "GPUInFlight", owner |-> "Receipt", disposition |-> "Advance", control |-> "Normal"],
  [from |-> "Encoding", to |-> "GPUInFlight", owner |-> "SelectedParallel", disposition |-> "Advance", control |-> "Normal"],
  [from |-> "Encoding", to |-> "GPUInFlight", owner |-> "GpuSubmission", disposition |-> "Advance", control |-> "Normal"],
  [from |-> "Encoding", to |-> "GPUInFlight", owner |-> "Receipt", disposition |-> "Advance", control |-> "Present"],
  [from |-> "Encoding", to |-> "GPUInFlight", owner |-> "SelectedParallel", disposition |-> "Advance", control |-> "Present"],
  [from |-> "GPUInFlight", to |-> "GPUInFlight", owner |-> "Receipt", disposition |-> "PayloadRetired", control |-> "Normal"],
  [from |-> "GPUInFlight", to |-> "Completed", owner |-> "GpuCompletion", disposition |-> "Completed", control |-> "Normal"],
  [from |-> "GPUInFlight", to |-> "Completed", owner |-> "Receipt", disposition |-> "Completed", control |-> "Normal"],
  [from |-> "GPUInFlight", to |-> "Completed", owner |-> "GpuCompletion", disposition |-> "Completed", control |-> "Present"],
  [from |-> "GPUInFlight", to |-> "Completed", owner |-> "Receipt", disposition |-> "Completed", control |-> "Present"],
  [from |-> "GPUInFlight", to |-> "Completed", owner |-> "DeviceLoss", disposition |-> "DeviceLost", control |-> "DeviceLoss"],
  [from |-> "Completed", to |-> "Reclaimed", owner |-> "Reclaim", disposition |-> "Completed", control |-> "Normal"],
  [from |-> "Completed", to |-> "Reclaimed", owner |-> "Reclaim", disposition |-> "PresentSettled", control |-> "Present"],
  [from |-> "Completed", to |-> "Completed", owner |-> "Queue", disposition |-> "FinishAdvance", control |-> "Normal"],
  [from |-> "Encoding", to |-> "Reclaimed", owner |-> "Queue", disposition |-> "NoGpuTerminal", control |-> "Normal"],
  [from |-> "RawOwned", to |-> "Reclaimed", owner |-> "Queue", disposition |-> "NoGpuTerminal", control |-> "Normal"],
  [from |-> "FinalOwned", to |-> "Reclaimed", owner |-> "Queue", disposition |-> "NoGpuTerminal", control |-> "Normal"],
  [from |-> "RawOwned", to |-> "Reclaimed", owner |-> "DeviceLoss", disposition |-> "FailStop", control |-> "DeviceLoss"],
  [from |-> "Encoding", to |-> "Reclaimed", owner |-> "DeviceLoss", disposition |-> "FailStop", control |-> "DeviceLoss"],
  [from |-> "RawOwned", to |-> "Reclaimed", owner |-> "PeImport", disposition |-> "BridgeReject", control |-> "Exception"],
  [from |-> "ProducerOwned", to |-> "Reclaimed", owner |-> "PeImport", disposition |-> "BridgeReject", control |-> "Exception"],
  [from |-> "ReplayBorrowed", to |-> "RawOwned", owner |-> "Queue", disposition |-> "PreEffectRollback", control |-> "Normal"],
  [from |-> "ReplayBorrowed", to |-> "Reclaimed", owner |-> "Replay", disposition |-> "ReplayFailure", control |-> "Exception"],
  [from |-> "Encoding", to |-> "Reclaimed", owner |-> "SerialEncode", disposition |-> "EncodeFailure", control |-> "Exception"],
  [from |-> "Encoding", to |-> "Reclaimed", owner |-> "SelectedParallel", disposition |-> "EncodeFailure", control |-> "Exception"],
  [from |-> "ProducerOwned", to |-> "Reclaimed", owner |-> "DeviceLoss", disposition |-> "FailStop", control |-> "DeviceLoss"],
  [from |-> "ReplayBorrowed", to |-> "Reclaimed", owner |-> "DeviceLoss", disposition |-> "FailStop", control |-> "DeviceLoss"],
  [from |-> "FinalOwned", to |-> "Reclaimed", owner |-> "DeviceLoss", disposition |-> "FailStop", control |-> "DeviceLoss"],
  [from |-> "Completed", to |-> "Reclaimed", owner |-> "DeviceLoss", disposition |-> "FailStop", control |-> "DeviceLoss"],
  [from |-> "GPUInFlight", to |-> "Reclaimed", owner |-> "DeviceLoss", disposition |-> "FailStop", control |-> "DeviceLoss"],
  [from |-> "RawOwned", to |-> "Reclaimed", owner |-> "Reset", disposition |-> "Reset", control |-> "Reset"],
  [from |-> "FinalOwned", to |-> "Reclaimed", owner |-> "Reset", disposition |-> "Reset", control |-> "Reset"],
  [from |-> "Encoding", to |-> "Reclaimed", owner |-> "Reset", disposition |-> "Reset", control |-> "Reset"],
  [from |-> "RawOwned", to |-> "Reclaimed", owner |-> "Teardown", disposition |-> "Teardown", control |-> "Teardown"],
  [from |-> "FinalOwned", to |-> "Reclaimed", owner |-> "Teardown", disposition |-> "Teardown", control |-> "Teardown"],
  [from |-> "Encoding", to |-> "Reclaimed", owner |-> "Teardown", disposition |-> "Teardown", control |-> "Teardown"],
  [from |-> "ProducerOwned", to |-> "Reclaimed", owner |-> "Teardown", disposition |-> "Teardown", control |-> "Teardown"],
  [from |-> "ReplayBorrowed", to |-> "Reclaimed", owner |-> "Teardown", disposition |-> "Teardown", control |-> "Teardown"],
  [from |-> "Completed", to |-> "Reclaimed", owner |-> "Teardown", disposition |-> "Teardown", control |-> "Teardown"],
  [from |-> "GPUInFlight", to |-> "Reclaimed", owner |-> "Teardown", disposition |-> "Teardown", control |-> "Teardown"]
}

LifecycleRow(from, to, owner, disposition, control) ==
  [from |-> from, to |-> to, owner |-> owner,
   disposition |-> disposition, control |-> control]

KnownLifecycleRow(from, to, owner, disposition, control) ==
  LifecycleRow(from, to, owner, disposition, control)\in LifecycleRows

Owners == {row.owner : row \in LifecycleRows}
Controls == {row.control : row \in LifecycleRows}
DispositionNames == {row.disposition : row \in LifecycleRows}

====
