#!/usr/bin/env python3

from __future__ import annotations

import argparse
import pathlib
import re
from dataclasses import dataclass


REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]
DEVICE_C_HEADER = REPO_ROOT / "include" / "dxmt9" / "device_c.h"
WINEMETAL_HEADER = REPO_ROOT / "include" / "dxmt9" / "winemetal.h"


@dataclass
class Param:
    signature_decl: str
    field_decl: str
    name: str


@dataclass
class Proto:
    return_type: str
    name: str
    params: list[Param]


PROTOTYPE_RE = re.compile(
    r"^(?P<ret>.+?)\s+(?P<name>(?:dxmt9c|dxmt9_winemetal)_[A-Za-z0-9_]+)\s*\((?P<params>.*)\)$",
    re.S,
)
WINEMETAL_PROTOS = [
    "dxmt9_u64 dxmt9_winemetal_compile_shader(const WinemetalShaderCompileRequest* request)",
    "const char* dxmt9_winemetal_shader_source(dxmt9_u64 shaderHandle)",
    "dxmt9_u64 dxmt9_winemetal_shader_source_size(dxmt9_u64 shaderHandle)",
    "void dxmt9_winemetal_destroy_shader(dxmt9_u64 shaderHandle)",
]


def normalize_whitespace(value: str) -> str:
    return re.sub(r"\s+", " ", value.strip())


def split_params(raw: str) -> list[str]:
    if not raw or raw == "void":
        return []
    depth = 0
    current: list[str] = []
    result: list[str] = []
    for ch in raw:
        if ch == "," and depth == 0:
            piece = "".join(current).strip()
            if piece:
                result.append(piece)
            current = []
            continue
        if ch in "([":
            depth += 1
        elif ch in ")]":
            depth -= 1
        current.append(ch)
    piece = "".join(current).strip()
    if piece:
        result.append(piece)
    return result


def parse_param(raw: str, index: int) -> Param:
    raw = normalize_whitespace(raw)
    array = ""
    array_match = re.search(r"(\[[^\]]+\])$", raw)
    body = raw
    if array_match:
        array = array_match.group(1)
        body = raw[: array_match.start()].rstrip()

    name_match = re.search(r"([A-Za-z_][A-Za-z0-9_]*)$", body)
    name = None
    type_part = body
    if name_match:
        candidate = name_match.group(1)
        prefix = body[: name_match.start()].rstrip()
        if prefix:
            name = candidate
            type_part = prefix
    if name is None:
        name = f"arg{index}"
        type_part = raw

    type_part = normalize_whitespace(type_part)
    field_type = type_part
    if array:
        field_type = f"{field_type}*"
    field_decl = f"{field_type} {name}"
    signature_decl = f"{type_part} {name}{array}".strip()
    return Param(signature_decl=signature_decl, field_decl=field_decl, name=name)


def parse_prototype(raw: str) -> Proto:
    raw = normalize_whitespace(raw)
    match = PROTOTYPE_RE.match(raw)
    if not match:
        raise ValueError(f"unsupported prototype: {raw!r}")
    params = [parse_param(param, index) for index, param in enumerate(split_params(match.group("params")))]
    return Proto(
        return_type=normalize_whitespace(match.group("ret")),
        name=match.group("name"),
        params=params,
    )


def collect_device_c_prototypes() -> list[Proto]:
    text = DEVICE_C_HEADER.read_text()
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    matches = re.finditer(
        r"([A-Za-z_][A-Za-z0-9_\s\*]*?\s+dxmt9c_[A-Za-z0-9_]+\s*\([^;]*?\)\s*;)",
        text,
        flags=re.S,
    )
    return [parse_prototype(match.group(1)[:-1]) for match in matches]


def collect_prototypes() -> list[Proto]:
    protos = collect_device_c_prototypes()
    protos.extend(parse_prototype(raw) for raw in WINEMETAL_PROTOS)
    return protos


def write_ops_header(path: pathlib.Path, protos: list[Proto]) -> None:
    lines: list[str] = []
    lines.append("// Generated by scripts/gen_wine_bridge.py. Do not edit by hand.")
    lines.append("#pragma once")
    lines.append("")
    lines.append('#include "dxmt9/device_c.h"')
    lines.append('#include "dxmt9/winemetal.h"')
    lines.append("")
    lines.append("namespace dxmt9::bridge {")
    lines.append("enum class BridgeOpcode : unsigned int {")
    for proto in protos:
        lines.append(f"  {proto.name},")
    lines.append("};")
    lines.append("")
    for proto in protos:
        lines.append(f"struct Args_{proto.name} {{")
        for param in proto.params:
            lines.append(f"  {param.field_decl};")
        if proto.return_type != "void":
            lines.append(f"  {proto.return_type} ret;")
        lines.append("};")
        lines.append("")
    lines.append(f"constexpr unsigned int kBridgeOpcodeCount = {len(protos)};")
    lines.append("}  // namespace dxmt9::bridge")
    lines.append("")
    path.write_text("\n".join(lines))


def failure_return_expr(return_type: str) -> str:
    return (
        f"dxmt9::bridge::bridgeFailure<{return_type}>(status)"
    )


def write_client_cpp(path: pathlib.Path, ops_header_name: str, protos: list[Proto]) -> None:
    lines: list[str] = []
    lines.append("// Generated by scripts/gen_wine_bridge.py. Do not edit by hand.")
    lines.append("#define WIN32_LEAN_AND_MEAN")
    lines.append('#include <windows.h>')
    lines.append("#include <type_traits>")
    lines.append("")
    lines.append('#include "dxmt9/device_c.h"')
    lines.append('#include "dxmt9/winemetal.h"')
    lines.append('#include "dxmt9/wineunixlib.h"')
    lines.append(f'#include "{ops_header_name}"')
    lines.append("")
    lines.append("extern \"C\" NTSTATUS dxmt9_bridge_unix_call(unsigned int code, void *args);")
    lines.append("")
    lines.append("namespace dxmt9::bridge {")
    lines.append("template <typename T>")
    lines.append("T bridgeFailure(NTSTATUS status) {")
    lines.append("  if constexpr (std::is_pointer_v<T>) {")
    lines.append("    return nullptr;")
    lines.append("  } else {")
    lines.append("    return static_cast<T>(status);")
    lines.append("  }")
    lines.append("}")
    lines.append("}  // namespace dxmt9::bridge")
    lines.append("")
    for proto in protos:
        param_decl = ", ".join(param.signature_decl for param in proto.params)
        lines.append(f'extern "C" {proto.return_type} {proto.name}({param_decl}) {{')
        lines.append(f"  dxmt9::bridge::Args_{proto.name} args{{}};")
        for param in proto.params:
            lines.append(f"  args.{param.name} = {param.name};")
        lines.append(
            f"  const NTSTATUS status = dxmt9_bridge_unix_call(static_cast<unsigned int>(dxmt9::bridge::BridgeOpcode::{proto.name}), &args);"
        )
        if proto.return_type == "void":
            lines.append("  (void)status;")
        else:
            lines.append(f"  if (status != DXMT9_STATUS_SUCCESS) return {failure_return_expr(proto.return_type)};")
            lines.append("  return args.ret;")
        lines.append("}")
        lines.append("")
    path.write_text("\n".join(lines))


def write_server_cpp(path: pathlib.Path, ops_header_name: str, protos: list[Proto]) -> None:
    lines: list[str] = []
    lines.append("// Generated by scripts/gen_wine_bridge.py. Do not edit by hand.")
    lines.append("#define WINE_UNIX_LIB 1")
    lines.append("")
    lines.append('#include "dxmt9/device_c.h"')
    lines.append('#include "dxmt9/winemetal.h"')
    lines.append('#include "dxmt9/wineunixlib.h"')
    lines.append(f'#include "{ops_header_name}"')
    lines.append("")
    lines.append('extern "C" NTSTATUS __wine_unix_lib_init(void) {')
    lines.append("  return DXMT9_STATUS_SUCCESS;")
    lines.append("}")
    lines.append("")
    lines.append("namespace {")
    for proto in protos:
        lines.append(f"NTSTATUS thunk_{proto.name}(void *opaque) {{")
        lines.append(f"  auto *args = reinterpret_cast<dxmt9::bridge::Args_{proto.name} *>(opaque);")
        lines.append("  if (!args) return DXMT9_STATUS_INVALID_PARAMETER;")
        call_args = ", ".join(f"args->{param.name}" for param in proto.params)
        if proto.return_type == "void":
            lines.append(f"  {proto.name}({call_args});")
        else:
            lines.append(f"  args->ret = {proto.name}({call_args});")
        lines.append("  return DXMT9_STATUS_SUCCESS;")
        lines.append("}")
        lines.append("")
    lines.append("}  // namespace")
    lines.append("")
    lines.append('extern "C" DECLSPEC_EXPORT const unixlib_entry_t __wine_unix_call_funcs[] = {')
    for proto in protos:
        lines.append(f"  thunk_{proto.name},")
    lines.append("};")
    lines.append("")
    lines.append('extern "C" DECLSPEC_EXPORT const unixlib_entry_t __wine_unix_call_wow64_funcs[] = {')
    for proto in protos:
        lines.append(f"  thunk_{proto.name},")
    lines.append("};")
    lines.append("")
    path.write_text("\n".join(lines))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--ops-header", required=True)
    parser.add_argument("--client-cpp", required=True)
    parser.add_argument("--server-cpp", required=True)
    args = parser.parse_args()

    protos = collect_prototypes()

    ops_header = pathlib.Path(args.ops_header)
    client_cpp = pathlib.Path(args.client_cpp)
    server_cpp = pathlib.Path(args.server_cpp)

    write_ops_header(ops_header, protos)
    write_client_cpp(client_cpp, ops_header.name, protos)
    write_server_cpp(server_cpp, ops_header.name, protos)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
